import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import icon from 'astro-icon';

// https://astro.build/config
export default defineConfig({
  output: 'static',
  site: 'https://programerso.app',
  integrations: [
    tailwind({ applyBaseStyles: false }),
    icon({
      include: {
        tabler: [
          'arrow-left',
          'arrow-right',
          'arrow-up',
          'award',
          'books',
          'bolt',
          'brain',
          'brand-javascript',
          'brand-python',
          'briefcase',
          'bug',
          'bulb',
          'calendar-stats',
          'certificate',
          'chart-bar',
          'check',
          'chevron-right',
          'clock',
          'command',
          'confetti',
          'cursor-text',
          'device-laptop',
          'download',
          'flag',
          'flame',
          'keyboard',
          'lock',
          'map',
          'mood-smile',
          'moon',
          'player-play',
          'refresh',
          'robot',
          'rosette',
          'search',
          'seedling',
          'settings',
          'sparkles',
          'sun',
          'sword',
          'target',
          'terminal',
          'trending-up',
          'trophy',
          'user',
          'x',
        ],
      },
    }),
  ],
});
